apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: rest-api-
  namespace: rest-api
  labels:
    app.kubernetes.io/instance: rest-api
    app.kubernetes.io/name: rest-api
    backstage.io/kubernetes-id: rest-api
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
    tekton.dev/pipeline: rest-api
spec:
  params:
  - name: APP_NAME
    value: rest-api
  - name: GIT_REPO
    value: https://github.com/bugbiteme/rest-api.git
  - name: GIT_REVISION
    value: main
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc:5000/rest-api/rest-api
  - name: PATH_CONTEXT
    value: .
  - name: GIT_USER_NAME
    value: bugbiteme
  - name: GIT_USER_EMAIL
    value: leon.s.levy@gmail.com
  pipelineRef:
    name: rest-api
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        labels:
          tekton.dev/pipeline: rest-api
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi